# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-03 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='comment',
            field=models.TextField(blank=True, help_text='Elaborate on what was spent on'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('FO', 'Food (Supermarket)'), ('ME', 'Meal'), ('TR', 'Transportation'), ('MA', 'Material Purchases'), ('FU', 'Fun'), ('MD', 'Medical'), ('HE', 'Health'), ('BI', 'Bills'), ('OT', 'Others')], max_length=2),
        ),
    ]
