# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-07 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20181007_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='spent',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
