# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-08 06:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20181007_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='spent',
        ),
    ]
