# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-08 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_remove_budget_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='active',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
